# Site settings
title: gui machiavelli
email: hey@guimachiavelli.com
description: Italian-brazilian programmer

# URLs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://guimachiavelli.com" # the base hostname & protocol for your site
permalink: /:slug
assets: assets

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: post

# Build settings
markdown: kramdown
exclude: [makefile, target.txt, readme.md]
plugins: [jekyll-responsive-image]

responsive_image:
    template: _includes/image.html
    default_quality: 100
    sizes:
        - width: 319
        - width: 639
        - width: 768
        - width: 1536
        - width: 1920
        - width: 2880
